# -*- coding: utf-8 -*-
"""0317daily.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQJGgkU7tBdvzCEcRnqqOql2mv-50qjl
"""

import pandas as pd

data = {
    "Title": [
        "Inception", "Interstellar", "The Dark Knight", "Parasite", "Avengers: Endgame",
        "The Matrix", "Gladiator", "Titanic", "Joker", "Mad Max: Fury Road",
        "The Godfather", "Pulp Fiction", "Schindler's List", "The Shawshank Redemption", "Fight Club"
    ],
    "Genre": [
        "Sci-Fi", "Sci-Fi", "Action", "Drama", "Action",
        "Sci-Fi", "Historical", "Romance", "Drama", "Action",
        "Crime", "Crime", "Drama", "Drama", "Drama"
    ],
    "Year": [
        2010, 2014, 2008, 2019, 2019,
        1999, 2000, 1997, 2019, 2015,
        1972, 1994, 1993, 1994, 1999
    ],
    "Director": [
        "Christopher Nolan", "Christopher Nolan", "Christopher Nolan", "Bong Joon-ho", "Anthony Russo",
        "Lana Wachowski", "Ridley Scott", "James Cameron", "Todd Phillips", "George Miller",
        "Francis Ford Coppola", "Quentin Tarantino", "Steven Spielberg", "Frank Darabont", "David Fincher"
    ],
"Rating": [
        8.8, 8.6, 9.0, 8.6, 8.4,
        8.7, 8.5, 7.8, 8.5, 8.1,
        9.2, 8.9, 8.9, 9.3, 8.8
    ],
    "Audience_Million": [
        100, 120, 150, 80, 200,
        90, 50, 220, 85, 75,
        110, 95, 85, 130, 70
    ],
    "Budget_Million": [
        160, 165, 185, 11, 356,
        63, 103, 200, 55, 150,
        6, 8, 22, 25, 63
    ]
}

df = pd.DataFrame(data)
print(df[df["Genre"] == "Action"]) # 1. 그냥 df한번만하면 false true를 보여주는 시리즈만 뜬다

print(df[df["Year"] >= 2010]) # 2

print(df[df["Rating"] >= 9.0]) # 3

print(df[df["Director"] == "Christopher Nolan"]) # 4

print(df[(df["Budget_Million"] >= 50) & (df["Budget_Million"] <= 200)]) # 5

print(df[df["Budget_Million"] >= 100])# 6

print(df[df["Audience_Million"] >= 100])# 7

print(df.sort_values("Year").iloc[-1])# 8 iloc을 사용하여 출력

print(df.sort_values("Year").iloc[0])# 9

print(df.iloc[:5])# 10

